version: '3'

services:
  app_telegram:
    build: .
    command: ["poetry", "run", "python", "start_telegram_bot.py"]

  app_api:
    build: .
    ports:
      - "8000:8000"
    command: ["poetry", "run", "python", "start_api_server.py"]

