"""prompt, output tables update

Revision ID: a6f73c2bf9e3
Revises: 1e06f9db6a2d
Create Date: 2023-06-04 02:06:32.229893

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import pgvector

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6f73c2bf9e3'
down_revision = '1e06f9db6a2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('output_messages', 'sender_id')
    op.add_column('prompt_messages', sa.Column('receiver_id', sa.Enum('SYSTEM', 'GPT_3_5_TURBO', 'GPT_4', 'DALL_E', name='system_user'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_messages', 'receiver_id')
    op.add_column('output_messages', sa.Column('sender_id', postgresql.ENUM('SYSTEM', 'GPT_3_5_TURBO', 'GPT_4', 'DALL_E', name='system_user'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
